### ISSUE TITLE
accès denied

### ISSUE THREAD

**Issue by Piermahe** [C2DH/mahec-digital-history#2]
![Capture d’écran 2024-10-15 à 12 51 17](https://github.com/user-attachments/assets/7878191f-f5d9-44c3-9441-19f2dea3e790)

As the printscreen says, I'm not allow to publish summaries on the page. Regards

**Comment by spapastamkou** [comment]
You must first accept the invite to be a collaborator - then you should normally have access. Please check your mails, normally you have a notification letting you know that you are invited to collaborate. 
![Capture d'écran 2024-10-15 224720](https://github.com/user-attachments/assets/37916642-c041-4108-ad69-d83016a57bcb)

**Comment by Piermahe** [comment]
Dear Dr. Papastamkou,
I’ve doubled checked my mails, and I didn’t receive any invitation.

Thanks for your time.

Best regards

Pierre Mahé

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by spapastamkou** [comment]
Can you check your spam file?

**Comment by spapastamkou** [comment]
En fait, je viens de vous envoyer une invitation au bon compte, apparemment j'avais invité un autre :-)

**Comment by spapastamkou** [comment]
Fixed.
