### ISSUE TITLE
can't add file

### ISSUE THREAD

**Issue by devajo22** [C2DH/mahec-digital-history#4]
I think I don't have access yet, as I need to fork the repository to add changes/files.

![Bild1](https://github.com/user-attachments/assets/ab892003-7b69-414c-a235-743cb7a5100c)

**Comment by spapastamkou** [comment]
Normally you should be able to do it now. I tried to push the commit you had created but I think you deleted it in the meantime so it was not possible that way. Please try to create your file (at your own convenience), and if you have problems, I will create it for you. I keep an eye. 

![Capture d'écran 2024-10-15 175206](https://github.com/user-attachments/assets/b1318e66-1293-4885-8223-8103e15c2a1e)

**Comment by spapastamkou** [comment]
Fixed.
